server.port: 8080
spring.application.name: spring-gateway-server
logging.level.web: TRACE
logging.level.org.springframework.web: TRACE
management.endpoints.web.exposure.include: gateway

nodes:
  1:
    uri: http://localhost:8081
    ref: 1
  2:
    uri: http://localhost:8082
    ref: 2
  3:
    uri: http://localhost:8083
    ref: 3   
